# GoReleaser configuration
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: hangar
    main: ./cmd/hangar
    binary: hangar
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: mnicholson
    name: hangar
  draft: false
  prerelease: auto
  mode: append
  name_template: "v{{.Version}}"
  header: |
    ## Hangar v{{.Version}}

    Terminal session manager for AI coding agents.

    ### Installation

    **Homebrew (recommended):**
    ```bash
    brew install mnicholson/tap/hangar
    ```

    **Quick Install:**
    ```bash
    curl -fsSL https://ghe.spotify.net/mnicholson/hangar/raw/master/install.sh | bash
    ```

    **Go Install:**
    ```bash
    go install ghe.spotify.net/mnicholson/hangar/cmd/hangar@v{{.Version}}
    ```
  footer: |
    ---

    **Full Changelog**: https://ghe.spotify.net/mnicholson/hangar/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - name: hangar
    repository:
      owner: mnicholson
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://ghe.spotify.net/mnicholson/hangar"
    description: "Terminal session manager for AI coding agents"
    license: "MIT"
    dependencies:
      - name: tmux
    test: |
      system "#{bin}/hangar", "version"
